### ISSUE TITLE
React 0.13 does not work: __reactAutoBindMap error

### ISSUE THREAD

**Issue by bshyong** [reactjs/react-rails#233]
This following error occurs when using React 0.13.1
`Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined`

Might be due to API changes in the new React version

It's referenced in this issue: https://github.com/facebook/react/issues/2661

```
Broken:

    React.renderComponent(
        BoxesView({count: counter++}),
        document.getElementById('grid')
    );
Working:
    React.render(
        React.createElement(BoxesView, {count: counter++}),
        document.getElementById('grid')
    );
```

**Comment by rmosolgo** [comment]
Thanks for reporting this issue. 

- What version of the gem are you using? 
- _When_ (or in what circumstances) does this error occur?

**Comment by bshyong** [comment]
@rmosolgo thanks for the quick response! From my Gemfile.lock it looks like the version is `1.0.0.pre`
```
  remote: git://github.com/reactjs/react-rails.git
  revision: a05c5af050311843846dc29c4e3ef6bc34bb89fe
  specs:
    react-rails (1.0.0.pre)
```

This happens on view templates that have render_react_component calls, e.g.:
```
<%= react_component('ConversationList', 'accountSlug' => @account.slug) %>
```
