### ISSUE TITLE
With Turbolinks: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by msojka** [reactjs/react-rails#553]
Help us help you! Please choose one:

- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

-------

I have a fairly complex spreadsheet-like page that I'm converting to React. There is one root component, multiple subcomponents and the bottom ones are table cells that are "in-place-editable".

Above the table is a dropdown with the links to the same page with different params. The links in the dropdown are not remote but use Turbolinks.

With Turbolinks on, the body of the page is rerendered, all components seem to be remounted and initialised properly however when I try to edit the table cell components I get following warning and it's not working:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you     called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`

The top components work as expected.

With Turbolinks off and full page refresh everything works as expected.

Thanks.

**Comment by rmosolgo** [comment]
In general, this happens when a React component is left in JS memory even after it has been removed from the DOM. 

For example, in our app, we have a component that, when you click it, it starts an AJAX request. When the AJAX request succeeds, it calls `setState` to update itself. BUT, if you change pages while the AJAX request is outstanding, we get that same error. This is because the component was unmounted (on page change) but the success handler was still executed, which called `setState` on an unmounted component. 

There are two ways to handle it: 

- Retain a reference to the AJAX request and abort it on `componentWillUnmount` 
- Use the (deprecated) `this.isMounted()` check in the success handler


Does that sound like a possibility in your case? Is there some way that a component instance could be held around even after a page changes?

**Comment by msojka** [comment]
Thanks @rmosolgo it sounds like a possible issue as there are lots of ajax requests happening on the page. Anyways I tested waited and making sure that all ajax requests were done before clicking on a Turbolinks link and still got same result.

Basically the warning appears on ajax successes on the next page that were not initiated on the previous page.

**Comment by rmosolgo** [comment]
does it tell you what component is triggering that warning? can you share the code for that component?

**Comment by msojka** [comment]
Related code from that component (it's in coffeescript):

```
  componentWillReceiveProps: (nextProps) =>
    @dispatch("receive", nextProps.value) if @state.submitted || @props.value != nextProps.value

  submit: (url, period, accountId, initValue, value) ->
    return {} if initValue == value
    data = JSON.stringify
      budget_entries:
        "#{period}": "#{accountId}": value
    $.ajax
      url: url
      type: "POST"
      dataType: "JSON"
      contentType: "application/json"
      processData: false
      data: data
      success: (data) =>
         # onReceive comes from props and is used to update state in the top component
        @onReceive(accountId, period, data[0].value)
    submitted: true

  receive: (value) ->
    initValue: value
    value: value
    submitted: false
```
