### ISSUE TITLE
Compile locally for production?

### ISSUE THREAD

**Issue by hopewise** [reactjs/react-rails#969]
Hi
I need to know how would I compile locally for production rather than at server, as my server resources can not afford the compilation process.
I was looking at this [issue](https://github.com/rails/webpacker/issues/1982#issuecomment-471511492) at `webpacker` 

I tried : `bundle exec rails webpacker:compile` , I got error:

`Error: Command 'webpacker:compile' not recognized`

but I am already have `gem 'webpacker'` in my Gemfile and its installed..

Can you please tell me how did you compile locally? I just need to locally compile the react project, not the whole assets.

**Comment by BookOfGreg** [comment]
```sh
react-rails-example-app (master)$ rails webpacker:compile
Webpacker is installed 🎉 🍰
Using /Users/gregmyers/source/react-rails-example-app/config/webpacker.yml file for setting up webpack paths
Compiling…
Compiled all packs in /Users/gregmyers/source/react-rails-example-app/public/packs
react-rails-example-app (master)$
```
I was able to `webpacker:compile` on the react-rails-example-app running webpacker 3.0.2 :
https://github.com/BookOfGreg/react-rails-example-app
Are you able to clone this repo down and run that command yourself to rule out problems in your env?

When you run `rails -T` do you see all the normal webpacker tools?
```
rails webpacker                          # Lists all available tasks in webpacker
rails webpacker:check_binstubs           # Verifies that bin/webpack & bin/webpack-dev-server ar...
rails webpacker:check_node               # Verifies if Node.js is installed
rails webpacker:check_yarn               # Verifies if Yarn is installed
rails webpacker:clobber                  # Remove the webpack compiled output directory
rails webpacker:compile                  # Compile javascript packs using webpack for production...
rails webpacker:install                  # Install webpacker in this application
rails webpacker:install:angular          # Install everything needed for Angular
rails webpacker:install:elm              # Install everything needed for Elm
rails webpacker:install:react            # Install everything needed for React
rails webpacker:install:vue              # Install everything needed for Vue
rails webpacker:verify_install           # Verifies if webpacker is installed
rails webpacker:yarn_install[arg1,arg2]  # Support for older Rails versions
```

**Comment by BookOfGreg** [comment]
That looks like an error with browserlist package that its outside of my knowledge I'm afraid.
Maybe related to these?
https://github.com/browserslist/browserslist/issues/266

Did you successfully manage to compile the react-rails-example-app?

**Comment by hopewise** [comment]
Yes, I managed to compile the react-rails-example-app successfully, but not my app 😿

**Comment by hopewise** [comment]
@BookOfGreg I found a solution to my problem, I just removed the css files from the project, and it compiled normally 👍 

Now I have to set `compile: false` at production for `config/webpacker.yml` ? as I already compiled locally, but then, I have to include `public/packs` in git ?

What do you recommend?

**Comment by BookOfGreg** [comment]
If you deploy via Git and you want to pre-compile your assets, then you will have to include the public packs you want to deploy with.

The process I follow is to build on CI, and then tar the public folder and deploy the `tar` to the server rather than from Git directly.

**Comment by hopewise** [comment]
I deploy via Capistrano.. I will set `compile: false` to save server power..

**Comment by BookOfGreg** [comment]
That sounds good, if it works for you would you please close the issue. Thank you.

**Comment by hopewise** [comment]
Sure, I will close it once I try deployment

**Comment by hopewise** [comment]
Okey, here is my deployment log:

```
..
..

Webpacker is installed 🎉 🍰
Using /var/www/myapp/releases/20190314152431/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:

Hash: e6a13856e42943387cfc
Version: webpack 3.12.0
Time: 7113ms
                             Asset       Size  Chunks             Chunk Names
    devops-fabf6ca4219f54c425c5.js     162 kB       0  [emitted]  devops
devops-fabf6ca4219f54c425c5.js.map     202 kB       0  [emitted]  devops
                     manifest.json  122 bytes          [emitted]
                  manifest.json.gz   83 bytes          [emitted]
 devops-fabf6ca4219f54c425c5.js.gz    50.9 kB          [emitted]
```

so, it seems that it **does** compile however, here is my `config/webpacker.yml`:

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: false

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: false

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

```

Any idea?
